layout: sidebar
style: ligth

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-github-contributions

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - stars
     
  limit: 10
  exclude:
    archived: false
    forks: true

social_media:
  linkedin: pedrofigs
  twitter: pedrofigssilva
